#!/bin/sh

chmod +x extract_pjsip.sh
./extract_pjsip.sh

chmod +x deps/pjsip/configure
chmod +x deps/pjsip/aconfigure
python3 setup.py build_ext --inplace "$@"
test -d build && python3 setup.py clean
